name: setup-cosmosdb-action
description: Set up a Cosmos DB Core SQL account for testing
inputs:
  connection-string-name:
    description: The name of the environment variable to fill with the Cosmos DB connection string
    required: true
  azure-credentials:
    description: The JSON blob containing the Azure login credentials. Required for cleaning up the Cosmos DB instance.
    required: true
  tag:
    description: The name of the component Cosmos DB is being used for. The Cosmos DB instance in Azure is tagged with this value.
    required: true
  api:
    description: The Cosmos DB API to set up. Choices are 'CoreSQL' (default) or 'Table'
    required: false
    default: CoreSQL
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js