name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os-name }}-${{ matrix.api }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-22.04 ]
        api: [ 'CoreSQL', 'Table' ]
        include:
          - os: windows-2022
            os-name: Windows
          - os: ubuntu-22.04
            os-name: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Azure login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
      - name: Run
        uses: ./
        with:
          connection-string-name: CosmosConnectionString
          azure-credentials: ${{ secrets.AZURE_ACI_CREDENTIALS }}
          tag: setup-cosmosdb-action
          api: ${{ matrix.api }}
      - name: Validate
        shell: pwsh
        run: |
          echo "CosmosConnectionString = $($Env:CosmosConnectionString)"
          if ( $Env:CosmosConnectionString -le 0 ) {
            throw "Environment variable  'CosmosConnectionString' not set."
          }
