name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.api }}-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        api: [ 'CoreSQL', 'Table' ]
        os: [ windows-2019, ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Azure login
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
      - name: Run
        uses: ./
        with:
          connection-string-name: CosmosConnectionString
          azure-credentials: ${{ secrets.AZURE_ACI_CREDENTIALS }}
          tag: setup-cosmosdb-action
          api: ${{ matrix.api }}
      - name: Validate
        shell: pwsh
        run: |
          echo "CosmosConnectionString = $($Env:CosmosConnectionString)"
          if ( $Env:CosmosConnectionString -le 0 ) {
            throw "Environment variable  'CosmosConnectionString' not set."
          }
