name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Azure login
        uses: azure/login@v1.3.0
        with:
          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
      - name: Run
        uses: ./
        with:
          connection-string-name: CosmosConnectionString
          azure-credentials: ${{ secrets.AZURE_ACI_CREDENTIALS }}
          azure-allowed-regions: ${{ secrets.COSMOS_ALLOWED_REGIONS }}
          tag: setup-cosmosdb-action
      - name: Validate
        shell: pwsh
        run: |
          if ( $Env:CosmosConnectionString -le 0 ) {
            throw "Environment variable  'CosmosConnectionString' not set."
          }